//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotter.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Spotter.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }

        internal static string Servers {
            get {
                return ResourceManager.GetString("Servers", resourceCulture);
            }
        }

        internal static string AuditLog {
            get {
                return ResourceManager.GetString("AuditLog", resourceCulture);
            }
        }

        internal static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }

        internal static string PostureScan {
            get {
                return ResourceManager.GetString("PostureScan", resourceCulture);
            }
        }

        internal static string Nis2 {
            get {
                return ResourceManager.GetString("Nis2", resourceCulture);
            }
        }

        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        internal static string UnderConstruction {
            get {
                return ResourceManager.GetString("UnderConstruction", resourceCulture);
            }
        }

        internal static string ServerCountBadge {
            get {
                return ResourceManager.GetString("ServerCountBadge", resourceCulture);
            }
        }

        internal static string Last24HoursBadge {
            get {
                return ResourceManager.GetString("Last24HoursBadge", resourceCulture);
            }
        }

        internal static string OpenAlerts {
            get {
                return ResourceManager.GetString("OpenAlerts", resourceCulture);
            }
        }

        internal static string CriticalEventsPerDay {
            get {
                return ResourceManager.GetString("CriticalEventsPerDay", resourceCulture);
            }
        }

        internal static string PostureAverage {
            get {
                return ResourceManager.GetString("PostureAverage", resourceCulture);
            }
        }

        internal static string Nis2Coverage {
            get {
                return ResourceManager.GetString("Nis2Coverage", resourceCulture);
            }
        }

        internal static string SecurityEventsChartTitle {
            get {
                return ResourceManager.GetString("SecurityEventsChartTitle", resourceCulture);
            }
        }

        internal static string TotalEventsSeries {
            get {
                return ResourceManager.GetString("TotalEventsSeries", resourceCulture);
            }
        }

        internal static string CriticalHighSeries {
            get {
                return ResourceManager.GetString("CriticalHighSeries", resourceCulture);
            }
        }

        internal static string RecentAuditEvents {
            get {
                return ResourceManager.GetString("RecentAuditEvents", resourceCulture);
            }
        }

        internal static string Nis2CoverageCaption {
            get {
                return ResourceManager.GetString("Nis2CoverageCaption", resourceCulture);
            }
        }

        internal static string PostureStatusTableTitle {
            get {
                return ResourceManager.GetString("PostureStatusTableTitle", resourceCulture);
            }
        }

        internal static string ServerColumn {
            get {
                return ResourceManager.GetString("ServerColumn", resourceCulture);
            }
        }

        internal static string ScoreColumn {
            get {
                return ResourceManager.GetString("ScoreColumn", resourceCulture);
            }
        }

        internal static string FindingsColumn {
            get {
                return ResourceManager.GetString("FindingsColumn", resourceCulture);
            }
        }

        internal static string FindingsSuffix {
            get {
                return ResourceManager.GetString("FindingsSuffix", resourceCulture);
            }
        }
    }
}
